
// Auth types

export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_START='USER_LOGIN_START'
export const USER_LOGIN_FAILED='USER_LOGIN_FAILED'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_START='USER_REGISTER_START'
export const USER_REGISTER_FAILED='USER_REGISTER_FAILED'
export const CART_TOTAL_QTY='CART_TOTAL_QTY'
export const SEARCH_RESULT='SEARCH_RESULT'

// Auth